### ISSUE TITLE
When using infinite-scroll to go to page x and then go to product and back to catalog, then it goes back to the wrong page

### ISSUE THREAD

**Issue by dehaanmedia** [shopigo/magento2-extension-infinite-scroll#4]
Magento 2.2.7.
12 products per page and 36 in total.
For example scroll to the bottom of this page.
https://www.staging.dehaanwebshop.nl/men/tops-men.html
And then click any product and go back to the catalog.
It goes to the page https://www.staging.dehaanwebshop.nl/men/tops-men.html?p=3 and only lists 12 products on the page, while it should show all products.

**Comment by dehaanmedia** [comment]
![before-click-product](https://user-images.githubusercontent.com/46077705/50498754-cbcff180-0a43-11e9-8d0e-bcb368eacc11.png)
![after-return-from-product](https://user-images.githubusercontent.com/46077705/50498757-ce324b80-0a43-11e9-9d0b-0d9ee428f6bd.png)
![catalog_config](https://user-images.githubusercontent.com/46077705/50498759-d12d3c00-0a43-11e9-8e9f-1f14294faa73.png)
![infinite-scroll-settings](https://user-images.githubusercontent.com/46077705/50498760-d2f6ff80-0a43-11e9-8d9f-a4dc4f3f9762.png)

**Comment by shopigo** [comment]
Hi,

To not add the page number to the URL (?p=2, p=3 etc.), you can comment the following code (file `view/frontend/web/js/product/list/infinite-scroll.js`, lines 473-491):

```
// Adjust the URL based on the top products wrapper shown for reasonable
// amounts of wrappers
if (Math.abs(scrollPos - this.pager.lastScrollPos) > ($(window).height() * 0.1)) {
	this.pager.lastScrollPos = scrollPos;
                    
	var self = this;
	$(this.options.productsContainer).each(function () {
		if (self.isPageMostlyVisible(this)) {
			if (typeof history.replaceState === 'function') {
				var pageUrl = $(this).attr(self.options.pageUrlAttr);
				if (pageUrl != window.location.href) {
					history.replaceState(null, null, pageUrl);
				}
			}
			return false;
		}
	});
}
```
