### ISSUE TITLE
Number of products miss

### ISSUE THREAD

**Issue by facetimer** [shopigo/magento2-extension-infinite-scroll#6]
Hello,

I lost the number of results in top.
i use Magento 2.2.6

Do you know where is the code which do that ?

**Comment by acharrex** [comment]
Hi,

The function taking care of that is defined here :
https://github.com/acharrex/magento2-extension-infinite-scroll/blob/master/view/frontend/web/js/product/list/infinite-scroll.js#L117

**Comment by facetimer** [comment]
Thank you !!

**Comment by nudylady** [comment]
If show number in top and show pager in bottom. These two elements should also be changed by ajax.
