### ISSUE TITLE
Ajax request error in loading items

### ISSUE THREAD

**Issue by ewayssoft** [shopigo/magento2-extension-infinite-scroll#7]
Hello Team,
After enabling the shopigo infinite scroll extension in my magento 2.3 website,page does not load 
the items and shows ajax request error.
Please help me out.
![screenshot](https://user-images.githubusercontent.com/48855781/54864997-d240e180-4d84-11e9-9c4c-c27593d07f15.png)

Thanks in advance
Regards 
ewayssoft

**Comment by acharrex** [comment]
Hi,

I recommend you to :
- Check whether the [AJAX listing extension](https://github.com/acharrex/magento2-extension-ajax-listing) is enabled
- Check the response of the AJAX request (with your browser console)
- Check Magento logs
- Check server logs

**Comment by ewayssoft** [comment]
Hello acharrex,
I have installed shopigo infinite scroll at app/code/Shopigo/CatalogInfiniteScroll
should i install ajax listing extension at app/code/Shopigo/CatalogAjaxListing with the former extension?

**Comment by acharrex** [comment]
Hi,

Yes exactly.
As documented here https://github.com/acharrex/magento2-extension-infinite-scroll#installation, the AJAX listing extension has to be installed and enabled.

**Comment by ewayssoft** [comment]
Hello Sir,
We have sorted out our problem.
Our extension is working if we have selected default Luma theme but it does
not work in other themes except default theme.
Please tell me that why this issue is arising and help us out.
Thanks in advance.

**Comment by acharrex** [comment]
What error do you encounter?

I recommend you to check if all elements defined here https://github.com/acharrex/magento2-extension-infinite-scroll/blob/master/view/frontend/web/js/product/list/infinite-scroll.js#L26 (lines 26-29) exist or not in your theme.
