### ISSUE TITLE
404 Loading productListCatalogInfiniteScroll.js

### ISSUE THREAD

**Issue by 0x15f** [shopigo/magento2-extension-infinite-scroll#9]
Can be recreated on https://staging.hue.com/women/shop-tights/fashion-tights?p=1

I debugged everything but I'm unsure why that file isn't being built, symlinked, etc. The module is enabled.

**Comment by 0x15f** [comment]
@acharrex have you been able to look into this?

**Comment by acharrex** [comment]
Hi,

Try to purge your cache and to re-deploy static files by following the official procedure :
https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-static-view.html

Deleting the contents of <your Magento install dir>/pub/static can help.

**Comment by 0x15f** [comment]
I've already tried that. The file is generated in the `Shopigo_CatalogInfiniteScroll` directory.

**Comment by 0x15f** [comment]
I believe this issue was specific to our template, I built a custom plugin that is working. I'll test this on a fresh Magento install and see if the issue persists.

**Comment by frostbitten** [comment]
I ran into this too. Turns out I forgot to install the other required extension:

> Important: this extension requires the [AJAX Listing extension by Shopigo](https://github.com/acharrex/magento2-extension-ajax-listing) (to install and enable)

So I ran the following and it worked:
```
composer require shopigo/magento2-extension-ajax-listing
```
